### PR TITLE
[New policies] Azure Cosmos DB - WAF - Reliability

### PR DESCRIPTION
**Pull request by seesharprun**
Two new policies to support upcoming WAF guidance around reliability:

- [x] `policyDefinitions/Cosmos DB/cosmos-db-audit-georeplication/azurepolicy.json`: Validates that there is at least two regions for the Azure Cosmos DB account.
- [x] `policyDefinitions/Cosmos DB/cosmos-db-audit-service-managed-failover/azurepolicy.json`: Validates that service-managed failover is enabled for the Azure Cosmos DB account.

### CODE REVIEW

**Review by techlake — COMMENTED** [review]
Please follow the contribution guidelines by submitting:
- 3 files per policy
- parameterize effect correctly
- include a guid name and type

**Review by techlake — CHANGES_REQUESTED** [review]
Please follow the contribution guidelines by submitting:
- 3 files per policy
- parameterize effect correctly
- include a guid name and type

**Comment by seesharprun** [comment]
Thanks @techlake, I will make those changes now.

**Comment by seesharprun** [comment]
@techlake, I have made those changes after reviewing the contributor guide. Thank you for the guidance.

**Review by techlake — APPROVED** [review]

**Pull request merged**
