### PR TITLE
Adding Azure Policy to manage Inbound Allowed NSG Security Rules with…

### PR DESCRIPTION
**Pull request by SebastianClaesson**
This policy audits/denies the creation of **inbound** security rules with the source "**Any**" and with "**Allow**" access action.

### CODE REVIEW

**Comment by SebastianClaesson** [comment]
This Azure policy will help out #220

**Comment by SebastianClaesson** [comment]
Example of compliance result:
Please note that the name of my policy is different from the one created.. but the definition is the same.
image

**Comment by techlake** [comment]
- Properties should be wrapped in a `"properties" {}` block
- `"effect": "deny"` is wrong. Use the parameter you defined above
- You need a name field (outside of properties which is a GUID.

**Comment by aschabus** [comment]
Please comply to the contribution guidance:
https://github.com/Azure/Community-Policy/blob/master/CONTRIBUTING.md

**Comment by aschabus** [comment]
@SebastianClaesson please note our comments in the PRs.
I apologize for not referring to you in the original comments.

**Comment by SebastianClaesson** [comment]
Hi @techlake & @aschabus ,

I have now followed the contribution guide in a new commit.

**Review by techlake — APPROVED** [review]

**Pull request merged**
