### PR TITLE
Add audit policy for resource access from other services and tenants

### PR DESCRIPTION
**Pull request by kimsyversen**
Hi!

Added an audit policy to more easily audit instances where SQL servers are configured to allow incoming network connections from other services within the same tenant or any Azure tenant. This configuration can be unintended, and one may not always realize the consequence of such a configuration.

### CODE REVIEW

**Comment by kimsyversen** [comment]
@microsoft-github-policy-service agree

**Comment by kimsyversen** [comment]
Is it me or is it the script?

````
Line |
  47 |  … essages, $path = Format-PolicyDefinition $content -category $category
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because
     | [System.Management.Automation.PSCustomObject] does not contain a method
     | named 'Remove'.
Error: Process completed with exit code 1.
```

**Comment by aschabus** [comment]
@kimsyversen sorry, it's a bug in our script.
We'll fix it and then we'll approve your policy.
Thanks for sharing it!

**Comment by kimsyversen** [comment]
> @kimsyversen sorry, it's a bug in our script.
> 
> We'll fix it and then we'll approve your policy.
> 
> Thanks for sharing it!

Thanks for clarifying! 😊

**Review by aschabus — APPROVED** [review]

**Pull request merged**
