### PR TITLE
Enforce Deny Local Authentication for Azure Storage Accounts (v1.0.0)

### PR DESCRIPTION
**Pull request by sergiusxp**
This pull request adds a new Azure Policy to ensure that all Azure Storage accounts are configured securely. It prevents the use of local authentication, a method that can make your data more vulnerable to unauthorized access.

By enforcing this policy, you'll strengthen the security of your cloud storage and reduce the risk of data breaches. This change is important for protecting sensitive information and complying with industry best practices.

The policy checks for three specific settings:
- `allowSharedKeyAccess`: Set to `true` indicates local authentication is possible.
- `allowBlobPublicAccess`: Set to `true` indicates local authentication is possible for blobs.
- `defaultToOAuthAuthentication`: Set to `false` allows local authentication as the default.
Denying the creation or update of storage accounts violating this rule: If any of the above conditions are met, the policy will **deny** the creation or update of the storage account.

### CODE REVIEW

**Comment by sergiusxp** [comment]
@microsoft-github-policy-service agree

**Comment by aschabus** [comment]
@sergiusxp can you please parameterize the effect?

**Comment by aschabus** [comment]
policy has the same name/id as "Deny deletion of storage account" => we need to change that

**Review by Joshua-Donovan — APPROVED** [review]
effect is parameter & name has been changed to a unique GUID.

**Pull request merged**
