### PR TITLE
More advanced PowerShell script with fixed files.

### PR DESCRIPTION
**Pull request by SebastianClaesson**
I've built the PowerShell script a bit more advanced now.
Fixes:
- Conforms to the PowerShell approved verbs.
- Assists in generating the correct azurepolicy.parameters.json and azurepolicy.rule.json.
- Fixing azurepolicy.json files with name that is not a GUID

I've ran it across all the Azure policy files in the repo, with lots of fixes to them.
Gone through a lot of the policies and I think it looks good :)

### CODE REVIEW

**Comment by techlake** [comment]
I'm still absorbing things. I had mine already mostly completed and will continue on that path.

**Comment by SebastianClaesson** [comment]
Ok! Do you wish me to close this pull request? :)

**Comment by techlake** [comment]
No, leave it. I'll  approve (gives you credit) and merge your ideas with mine. However, do not spend more time on it. I'll likely finish the scripts today US CDT.



Heinrich Gantenbein (he/him)
Senior Principal Consultant Cybersecurity

Microsoft
Mobile: +1-678-469-9575
***@***.******@***.***>
Designing and Developing Secure Azure Solutions<https://azsec.tech/get>

[A picture containing text, sign, blue  Description automatically generated]   [Logo  Description automatically generated]    [A picture containing graphical user interface  Description automatically generated]     [Designing and Developing Secure Azure Solutions] <https://azsec.tech/get>
[Microsoft Logo]

**Comment by techlake** [comment]
I will not approve/merge it. However, please leave it open, so, I can reference.

**Comment by SebastianClaesson** [comment]
Ok! I'll leave it open. Thank you!

**Comment by techlake** [comment]
I will not approve/merge it. However, please leave it open, so I can reference the script.

**Comment by techlake** [comment]
Closing pull request as superceded.

**Pull request closed without merging**
