### PR TITLE
new azure policy

### PR DESCRIPTION
**Pull request by psinnathurai**
Adding new Azure Policy for Multiple Tags to inherit from Resource Group.

### CODE REVIEW

**Review by aschabus — APPROVED** [review]

**Comment by aschabus** [comment]
@psinnathurai can you please add the information according to the check above.
e.g.
- Metadata category is not supplied and category parameter is empty.
- Policy name missing or not a GUID
- Policy metadata version not found. Fix using 1.0.0.
- Policy effect is hard coded. 
- policyType (Custom) is not allowed, fix by removing it from the definition.

**Comment by psinnathurai** [comment]
I have added the missing informations.

**Comment by aschabus** [comment]
@psinnathurai thanks a lot for the changes.
FYI: in general we would recommend to use a initiative for this; the policy guards one tag and the initiative has five (built-in) policies in it.

**Comment by aschabus** [comment]
@psinnathurai it seems that the change in the deploy-service-health-alert-incidents policy slipped in from a fork outside of this repository, so we removed it.

**Comment by psinnathurai** [comment]
> @psinnathurai thanks a lot for the changes. FYI: in general we would recommend to use a initiative for this; the policy guards one tag and the initiative has five (built-in) policies in it.

Thanks for that! I will try this next time.

**Pull request merged**
