### PR TITLE
Network policies for various purposes

### PR DESCRIPTION
**Pull request by vegazbabz**
3 network policies for various purposes. See policy descriptions for further info.

### CODE REVIEW

**Review by techlake — CHANGES_REQUESTED** [review]
Hi Niclas,
We want to tighten the naming. Instead of Audit or Deny in the displayName, use Require instead

**Comment by vegazbabz** [comment]
While I do like that idea, I do not see it fit for these 3 policies:
- Deny inbound DNAT on Azure Firewalls
- Audit changes to route tables (UDRs)
- Deploy a user-defined route to a VNET with specific routes

We do not want to require inbound DNAT or require changes to UDRs.

**Comment by techlake** [comment]
Agreed on #2 and #3

How about #1 (since it has Audit or Deny which can be confusing), say "Prevent inbound DNAT on Azure Firewalls". However, if you think it is better with Deny, I will approve.

PS: The approval team did discuss this topic today and it is a tricky subject

Heinrich Gantenbein

**Comment by vegazbabz** [comment]
I agree with that. Changed PR.

**Review by techlake — APPROVED** [review]

**Pull request merged**
