### PR TITLE
[New] Log Analytics Workspace require retention in days

### LINKED ISSUE #373: [New] Log Analytics Workspace require retention in days
* #374

### PR DESCRIPTION
**Pull request by BoSoeborgPetersen**
* Resolves #373

### CODE REVIEW

**Comment by aschabus** [comment]
Can you please parameterize the number of days ans set the default to 90 instead of having a hard value of 90 days.

**Comment by aschabus** [comment]
Can you please parameterize the number of days ans set the default to 90 instead of having a hard value of 90 days.

**Review by aschabus — CHANGES_REQUESTED** [review]
Can you please parameterize the number of days ans set the default to 90 instead of have a hard value of 90 days.

**Comment by BoSoeborgPetersen** [comment]
Yes of course.
It is done.

**Review by aschabus — APPROVED** [review]

**Pull request merged**
