### PR TITLE
Adding category "Network" for each network provider policy

### PR DESCRIPTION
**Pull request by SebastianClaesson**
Adding the metadata object with Category = Network for each Azure Policy.
Fixed identation for each policy to be 4 spaces instead of 2 spaces to provide a consistency across the json files.

Some policies has more specific category set, such as "Azure DNS", these have not had their category updated.
I've only updated tags on policies without the metadata category attribute.

### CODE REVIEW

**Comment by techlake** [comment]
Same as other submissions please fix properties, name on all of them
Plus unresolved Git conflicts

**Comment by techlake** [comment]
@SebastianClaesson  https://github.com/Azure/Community-Policy/blob/master/CONTRIBUTING.md#contribution-guide

**Comment by techlake** [comment]
@SebastianClaesson https://github.com/Azure/Community-Policy/blob/master/CONTRIBUTING.md#contribution-guide

**Comment by SebastianClaesson** [comment]
Hi @techlake , I'll go through all of these. Seems they all might have been created since before the contribution guide. I'll submit a new PR once it's done.

**Comment by techlake** [comment]
Thank you.

**Pull request closed without merging**
