### PR TITLE
Added subscription diagnostic settings policies

### PR DESCRIPTION
**Pull request by ShachafGoldstein**

### CODE REVIEW

**Comment by mrajess** [comment]
Would this be a duplicate of: https://github.com/Azure/Community-Policy/tree/master/Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-log-analytics

**Comment by ShachafGoldstein** [comment]
Yes it is, i missed it, this adds one folder for the same one and another that is different 
The one which does the same is a bit different since it won't fail for settings with different names

I can revise this to change the existing one and only add the new one, or keep them both and maybe add a README to suggest what is the difference between the two

**Comment by mrajess** [comment]
I think a README would do. Thanks!

**Comment by ShachafGoldstein** [comment]
Done

**Pull request merged**
